<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>xkyss :: Test</name>
    <groupId>com.xkyss</groupId>
    <artifactId>xkyss-test</artifactId>
    <version>2024.03.20</version>
    <packaging>pom</packaging>

    <modules>
        <module>xkyss-test-etcd</module>
        <module>xkyss-test-kafka</module>
        <module>xkyss-test-vertx</module>
        <module>xkyss-test-redis</module>
        <module>xkyss-test-cdc</module>
        <module>xkyss-test-grpc</module>
        <module>xkyss-test-easy-query</module>
    </modules>

    <properties>
        <!-- project -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- maven -->
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <maven-shade-plugin.version>3.4.1</maven-shade-plugin.version>
        <proguard-maven-plugin.version>2.6.0</proguard-maven-plugin.version>
        <junit.version>5.11.3</junit.version>
        <vertx.version>4.5.7</vertx.version>
        <jackson.version>2.16.1</jackson.version>
        <logback-classic.version>1.2.3</logback-classic.version>
        <slf4j.version>1.7.36</slf4j.version>
    </properties>

    <dependencies>
        <!-- 全局单元测试 -->
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-junit5</artifactId>
            <version>${vertx.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven-shade-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.github.wvengen</groupId>
                    <artifactId>proguard-maven-plugin</artifactId>
                    <version>${proguard-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>